on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Build and Verify Images Locally

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build
      run:
        mvn clean package

